### PR TITLE
Add permissions v2 support

### PR DESCRIPTION
**Pull request by GoogolGenius**
WIP:
https://github.com/hikari-py/hikari/pull/1148
https://github.com/FasterSpeeding/Tanjun/pull/296

### CODE REVIEW

**Comment by thesadru** [comment]
Maybe should just add `**kwargs` there at this point in case I miss a feature again.

**Comment by GoogleGenius** [comment]
Eh, then you lose type hints because you would annotate `*args` and `**kwargs` with something like `typing.Any` or whatever.

**Comment by thesadru** [comment]
Just in addition to the already known args.

**Comment by GoogleGenius** [comment]
I think I messed up the commit history lol

**Comment by GoogleGenius** [comment]
I have no idea why the tests are failing

**Pull request closed without merging**
